# Generated by Django 2.2.2 on 2019-06-15 09:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('balance', models.IntegerField()),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='income_and_expense.Account')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pay_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('amount', models.PositiveIntegerField()),
                ('undecided', models.BooleanField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='income_and_expense.Method')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pay_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('period_day', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('amount', models.PositiveIntegerField()),
                ('undecided', models.BooleanField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='income_and_expense.Method')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='income_and_expense.Bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='income_and_expense.User'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pay_date', models.DateField(verbose_name='payment date')),
                ('amount', models.PositiveIntegerField()),
                ('undecided', models.BooleanField()),
                ('done', models.BooleanField(default=False)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='income_and_expense.Method')),
            ],
            options={
                'unique_together': {('name', 'pay_date')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pay_date', models.DateField(verbose_name='payment date')),
                ('period_date', models.DateField(null=True, verbose_name='period date')),
                ('amount', models.PositiveIntegerField()),
                ('undecided', models.BooleanField()),
                ('done', models.BooleanField(default=False)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='income_and_expense.Method')),
            ],
            options={
                'unique_together': {('name', 'pay_date'), ('name', 'period_date')},
            },
        ),
        migrations.CreateModel(
            name='DefaultIncomeMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('def_inc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_and_expense.DefaultIncome')),
            ],
            options={
                'unique_together': {('month', 'def_inc')},
            },
        ),
        migrations.CreateModel(
            name='DefaultExpenseMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('def_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_and_expense.DefaultExpense')),
            ],
            options={
                'unique_together': {('month', 'def_exp')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('bank', 'user')},
        ),
    ]
