# Generated by Django 2.2.2 on 2020-02-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income_and_expense', '0002_auto_20200208_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settlement',
        ),
    ]
