# Generated by Django 2.2.13 on 2021-06-29 12:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income_and_expense', '0005_auto_20200510_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_type', models.CharField(choices=[('today', '即日'), ('later', '後日')], max_length=10)),
                ('pay_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('limit_day_of_this_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('undecided', models.BooleanField()),
                ('done', models.BooleanField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='income_and_expense.Method')),
            ],
            options={
                'verbose_name': '支出（テンプレート）',
                'verbose_name_plural': '支出（テンプレート）',
            },
        ),
    ]
