# Generated by Django 2.2.13 on 2021-06-29 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_and_expense', '0007_auto_20210629_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateexpense',
            name='limit_day_of_this_month',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AlterField(
            model_name='templateexpense',
            name='pay_day',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
