# Generated by Django 2.2.13 on 2021-07-04 04:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income_and_expense', '0010_auto_20210630_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pay_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('first_year', models.PositiveIntegerField()),
                ('first_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('last_year', models.PositiveIntegerField()),
                ('last_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('amount_first', models.PositiveIntegerField()),
                ('amount_from_second', models.PositiveIntegerField()),
                ('undecided', models.BooleanField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='income_and_expense.Method')),
            ],
            options={
                'verbose_name': 'ローン',
                'verbose_name_plural': 'ローン',
            },
        ),
    ]
