# Generated by Django 4.0.6 on 2022-07-18 15:15

from django.db import migrations, models


def apply_state_settings(apps, schema_editor):
    # DefaultExpenseモデルを取得
    DefaultExpense = apps.get_model('income_and_expense', 'DefaultExpense')

    for def_exp in DefaultExpense.objects.all():
        if def_exp.undecided == True:
            def_exp.state = 0
        else:
            def_exp.state = 1
        def_exp.save()

    # DefaultIncomeモデルを取得
    DefaultIncome = apps.get_model('income_and_expense', 'DefaultIncome')

    for def_inc in DefaultIncome.objects.all():
        if def_inc.undecided == True:
            def_inc.state = 0
        else:
            def_inc.state = 1
        def_inc.save()

    # Loanモデルを取得
    Loan = apps.get_model('income_and_expense', 'Loan')

    for loan in Loan.objects.all():
        if loan.undecided == True:
            loan.state = 0
        else:
            loan.state = 1
        loan.save()

    # TemplateExpenseモデルを取得
    TemplateExpense = apps.get_model('income_and_expense', 'TemplateExpense')

    for template_exps in TemplateExpense.objects.all():
        if template_exps.undecided == True:
            template_exps.state = 0
        elif template_exps.done == False:
            template_exps.state = 1
        else:
            template_exps.state = 2
        template_exps.save()


class Migration(migrations.Migration):

    dependencies = [
        ('income_and_expense', '0013_remove_income_done_remove_income_undecided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultexpense',
            name='state',
            field=models.IntegerField(choices=[(0, '未定'), (1, '確定'), (2, '完了')], default=0),
        ),
        migrations.AddField(
            model_name='defaultincome',
            name='state',
            field=models.IntegerField(choices=[(0, '未定'), (1, '確定'), (2, '完了')], default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='state',
            field=models.IntegerField(choices=[(0, '未定'), (1, '確定'), (2, '完了')], default=0),
        ),
        migrations.AddField(
            model_name='templateexpense',
            name='state',
            field=models.IntegerField(choices=[(0, '未定'), (1, '確定'), (2, '完了')], default=0),
        ),
        migrations.RunPython(apply_state_settings, None),        
        migrations.RemoveField(
            model_name='defaultexpense',
            name='undecided',
        ),
        migrations.RemoveField(
            model_name='defaultincome',
            name='undecided',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='undecided',
        ),
        migrations.RemoveField(
            model_name='templateexpense',
            name='done',
        ),
        migrations.RemoveField(
            model_name='templateexpense',
            name='undecided',
        ),
        migrations.AlterField(
            model_name='expense',
            name='state',
            field=models.IntegerField(choices=[(0, '未定'), (1, '確定'), (2, '完了')], default=0),
        ),
        migrations.AlterField(
            model_name='income',
            name='state',
            field=models.IntegerField(choices=[(0, '未定'), (1, '確定'), (2, '完了')], default=0),
        )
    ]
