# Generated by Django 4.0.6 on 2026-04-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_and_expense', '0015_expense_memo_income_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
