from income_and_expense.const import const

const.SHOWN_NAME_NAME = '名前'
const.SHOWN_NAME_BANK = '銀行'
const.SHOWN_NAME_USER = 'ユーザー'
const.SHOWN_NAME_ACCOUNT = '口座'
const.SHOWN_NAME_BALANCE = '残高'
const.SHOWN_NAME_METHOD = '支払方法'
const.SHOWN_NAME_DATE_TYPE = '日付タイプ'
const.SHOWN_NAME_PAY_DATE = '支払日'
const.SHOWN_NAME_PAY_DAY = '支払日'
const.SHOWN_NAME_LIMIT_DAY_OF_THIS_MONTH = '支払月切替期日'
const.SHOWN_NAME_AMOUNT = '金額'
const.SHOWN_NAME_EXPENSE = '支出'
const.SHOWN_NAME_INCOME = '収入'
const.SHOWN_NAME_DEFAULT = '（デフォルト）'
const.SHOWN_NAME_TEMPLATE = '（テンプレート）'
const.SHOWN_NAME_APPLY_MONTH = '適用月'
const.SHOWN_NAME_MONTH = '月'
const.SHOWN_NAME_DONE = '完了'
const.SHOWN_NAME_NOT_DONE = '未完了'
const.SHOWN_NAME_UNDECIDED = '未定'
const.SHOWN_NAME_DECIDED = '確定'
const.SHOWN_NAME_CHANGE_TO = 'に変更'